server:
  port: 8080

spring:
  datasource:
    username: root
    password: YeKe1403483531.
    url: jdbc:mysql://localhost:3306/server?
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-flex:
  global-config:
    print-banner: false